create table if not exists projects(
    id integer primary key generated by default as identity,
    name text not null check (name<>''),
    priority integer not null,
    description text,
    deliverydate date not null
);

create table if not exists task(
    id integer primary key generated by default as identity,
    name text not null check (name<>''),
    done boolean,
    projectid integer references projects(id)
);

{
	"name":"Make a data science web App",
	"priority":1,
	"description":"Using python",
	"deliverydate":"2019-10-06"
}

{
	"name":"Setup Vue",
	"done":false,
	"projectId":2
}